/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --env-interface GeneratedCloudflareEnv --include-runtime false` (hash: af5965d571f3f40007233f98c5e9ff13)
interface __BaseEnv_GeneratedCloudflareEnv {
	DB: D1Database;
	AI: Ai;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_GeneratedCloudflareEnv {}
}
interface GeneratedCloudflareEnv extends __BaseEnv_GeneratedCloudflareEnv {}
