import type { Icon, IconProps } from '@phosphor-icons/react';
import { ArrowCounterClockwiseIcon as ArrowCounterClockwiseGlyph } from '@phosphor-icons/react/dist/ssr/ArrowCounterClockwise';
import { ArrowDownIcon as ArrowDownGlyph } from '@phosphor-icons/react/dist/ssr/ArrowDown';
import { ArrowLeftIcon as ArrowLeftGlyph } from '@phosphor-icons/react/dist/ssr/ArrowLeft';
import { ArrowSquareOutIcon as ArrowSquareOutGlyph } from '@phosphor-icons/react/dist/ssr/ArrowSquareOut';
import { ArrowUpIcon as ArrowUpGlyph } from '@phosphor-icons/react/dist/ssr/ArrowUp';
import { ArrowUpLeftIcon as ArrowUpLeftGlyph } from '@phosphor-icons/react/dist/ssr/ArrowUpLeft';
import { ArrowUpRightIcon as ArrowUpRightGlyph } from '@phosphor-icons/react/dist/ssr/ArrowUpRight';
import { BookOpenTextIcon as BookOpenTextGlyph } from '@phosphor-icons/react/dist/ssr/BookOpenText';
import { BookmarkSimpleIcon as BookmarkSimpleGlyph } from '@phosphor-icons/react/dist/ssr/BookmarkSimple';
import { BroadcastIcon as BroadcastGlyph } from '@phosphor-icons/react/dist/ssr/Broadcast';
import { CalendarDotsIcon as CalendarDotsGlyph } from '@phosphor-icons/react/dist/ssr/CalendarDots';
import { CaretDownIcon as CaretDownGlyph } from '@phosphor-icons/react/dist/ssr/CaretDown';
import { CaretLeftIcon as CaretLeftGlyph } from '@phosphor-icons/react/dist/ssr/CaretLeft';
import { CaretRightIcon as CaretRightGlyph } from '@phosphor-icons/react/dist/ssr/CaretRight';
import { ChatCircleTextIcon as ChatCircleTextGlyph } from '@phosphor-icons/react/dist/ssr/ChatCircleText';
import { CheckIcon as CheckGlyph } from '@phosphor-icons/react/dist/ssr/Check';
import { CheckCircleIcon as CheckCircleGlyph } from '@phosphor-icons/react/dist/ssr/CheckCircle';
import { ChecksIcon as ChecksGlyph } from '@phosphor-icons/react/dist/ssr/Checks';
import { ClockCounterClockwiseIcon as ClockCounterClockwiseGlyph } from '@phosphor-icons/react/dist/ssr/ClockCounterClockwise';
import { CopySimpleIcon as CopySimpleGlyph } from '@phosphor-icons/react/dist/ssr/CopySimple';
import { DownloadSimpleIcon as DownloadSimpleGlyph } from '@phosphor-icons/react/dist/ssr/DownloadSimple';
import { EyeIcon as EyeGlyph } from '@phosphor-icons/react/dist/ssr/Eye';
import { FileTextIcon as FileTextGlyph } from '@phosphor-icons/react/dist/ssr/FileText';
import { FlaskIcon as FlaskGlyph } from '@phosphor-icons/react/dist/ssr/Flask';
import { FunnelSimpleIcon as FunnelSimpleGlyph } from '@phosphor-icons/react/dist/ssr/FunnelSimple';
import { GlobeHemisphereEastIcon as GlobeHemisphereEastGlyph } from '@phosphor-icons/react/dist/ssr/GlobeHemisphereEast';
import { InfoIcon as InfoGlyph } from '@phosphor-icons/react/dist/ssr/Info';
import { ListIcon as ListGlyph } from '@phosphor-icons/react/dist/ssr/List';
import { MagnifyingGlassIcon as MagnifyingGlassGlyph } from '@phosphor-icons/react/dist/ssr/MagnifyingGlass';
import { MapPinIcon as MapPinGlyph } from '@phosphor-icons/react/dist/ssr/MapPin';
import { PlusIcon as PlusGlyph } from '@phosphor-icons/react/dist/ssr/Plus';
import { PrinterIcon as PrinterGlyph } from '@phosphor-icons/react/dist/ssr/Printer';
import { PulseIcon as PulseGlyph } from '@phosphor-icons/react/dist/ssr/Pulse';
import { QuestionIcon as QuestionGlyph } from '@phosphor-icons/react/dist/ssr/Question';
import { ScalesIcon as ScalesGlyph } from '@phosphor-icons/react/dist/ssr/Scales';
import { ScanIcon as ScanGlyph } from '@phosphor-icons/react/dist/ssr/Scan';
import { ShieldCheckIcon as ShieldCheckGlyph } from '@phosphor-icons/react/dist/ssr/ShieldCheck';
import { SparkleIcon as SparkleGlyph } from '@phosphor-icons/react/dist/ssr/Sparkle';
import { SquaresFourIcon as SquaresFourGlyph } from '@phosphor-icons/react/dist/ssr/SquaresFour';
import { SunHorizonIcon as SunHorizonGlyph } from '@phosphor-icons/react/dist/ssr/SunHorizon';
import { TrendUpIcon as TrendUpGlyph } from '@phosphor-icons/react/dist/ssr/TrendUp';
import { UsersThreeIcon as UsersThreeGlyph } from '@phosphor-icons/react/dist/ssr/UsersThree';
import { WarningIcon as WarningGlyph } from '@phosphor-icons/react/dist/ssr/Warning';
import { XIcon as XGlyph } from '@phosphor-icons/react/dist/ssr/X';

// One visual family, imported per icon for both server and client rendering.
function uiIcon(Glyph: Icon, weight: IconProps['weight'] = 'duotone') {
  return function UiIcon({ strokeWidth, className, ...props }: IconProps) {
    void strokeWidth;
    return <Glyph size={20} weight={weight} aria-hidden="true" focusable="false" {...props} className={'ui-icon ' + (className || '')}/>;
  };
}

export const ArrowLeft = /* @__PURE__ */ uiIcon(ArrowLeftGlyph, 'regular');
export const ArrowUpLeft = /* @__PURE__ */ uiIcon(ArrowUpLeftGlyph, 'regular');
export const ArrowUpRight = /* @__PURE__ */ uiIcon(ArrowUpRightGlyph, 'regular');
export const ArrowUp = /* @__PURE__ */ uiIcon(ArrowUpGlyph, 'regular');
export const ArrowDown = /* @__PURE__ */ uiIcon(ArrowDownGlyph, 'regular');
export const BookOpen = /* @__PURE__ */ uiIcon(BookOpenTextGlyph);
export const Check = /* @__PURE__ */ uiIcon(CheckGlyph, 'regular');
export const CheckCheck = /* @__PURE__ */ uiIcon(ChecksGlyph, 'regular');
export const ChevronLeft = /* @__PURE__ */ uiIcon(CaretLeftGlyph, 'regular');
export const ChevronDown = /* @__PURE__ */ uiIcon(CaretDownGlyph, 'regular');
export const ChevronRight = /* @__PURE__ */ uiIcon(CaretRightGlyph, 'regular');
export const CircleHelp = /* @__PURE__ */ uiIcon(QuestionGlyph);
export const Compass = /* @__PURE__ */ uiIcon(BroadcastGlyph);
export const Download = /* @__PURE__ */ uiIcon(DownloadSimpleGlyph);
export const ExternalLink = /* @__PURE__ */ uiIcon(ArrowSquareOutGlyph, 'regular');
export const FileCheck2 = /* @__PURE__ */ uiIcon(FileTextGlyph);
export const FileText = /* @__PURE__ */ uiIcon(FileTextGlyph);
export const Globe2 = /* @__PURE__ */ uiIcon(GlobeHemisphereEastGlyph);
export const LayoutGrid = /* @__PURE__ */ uiIcon(SquaresFourGlyph);
export const ListFilter = /* @__PURE__ */ uiIcon(FunnelSimpleGlyph);
export const Menu = /* @__PURE__ */ uiIcon(ListGlyph, 'regular');
export const MessageCircle = /* @__PURE__ */ uiIcon(ChatCircleTextGlyph);
export const Plus = /* @__PURE__ */ uiIcon(PlusGlyph, 'regular');
export const Search = /* @__PURE__ */ uiIcon(MagnifyingGlassGlyph);
export const ShieldCheck = /* @__PURE__ */ uiIcon(ShieldCheckGlyph);
export const Sparkles = /* @__PURE__ */ uiIcon(SparkleGlyph);
export const Sun = /* @__PURE__ */ uiIcon(SunHorizonGlyph);
export const TrendingUp = /* @__PURE__ */ uiIcon(TrendUpGlyph, 'regular');
export const Users = /* @__PURE__ */ uiIcon(UsersThreeGlyph);
export const X = /* @__PURE__ */ uiIcon(XGlyph, 'regular');
export const MapPin = /* @__PURE__ */ uiIcon(MapPinGlyph);
export const CalendarDays = /* @__PURE__ */ uiIcon(CalendarDotsGlyph);
export const Info = /* @__PURE__ */ uiIcon(InfoGlyph);
export const Activity = /* @__PURE__ */ uiIcon(PulseGlyph);
export const Scale = /* @__PURE__ */ uiIcon(ScalesGlyph);
export const Clock3 = /* @__PURE__ */ uiIcon(ClockCounterClockwiseGlyph);
export const FlaskConical = /* @__PURE__ */ uiIcon(FlaskGlyph);
export const CheckCircle2 = /* @__PURE__ */ uiIcon(CheckCircleGlyph);
export const AlertTriangle = /* @__PURE__ */ uiIcon(WarningGlyph);
export const Bookmark = /* @__PURE__ */ uiIcon(BookmarkSimpleGlyph);
export const Printer = /* @__PURE__ */ uiIcon(PrinterGlyph);
export const RotateCcw = /* @__PURE__ */ uiIcon(ArrowCounterClockwiseGlyph, 'regular');
export const Copy = /* @__PURE__ */ uiIcon(CopySimpleGlyph);
export const ScanText = /* @__PURE__ */ uiIcon(ScanGlyph);
export const Eye = /* @__PURE__ */ uiIcon(EyeGlyph);
export const Radar = /* @__PURE__ */ uiIcon(BroadcastGlyph);
